### ISSUE TITLE
New Threats are getting added when close the add new threats window is closed

### ISSUE THREAD

**Issue by itsdheerajdp** [OWASP/threat-dragon#894] opened 2024-03-01 15:55 UTC
**Describe the bug**:
Currently if we are clicking on [New Threat] Button then it will add the threat however if click on apply or not. By clicking on close button is also resulting in adding new threats. Visuals are shown below

[screen-capture.webm](https://github.com/OWASP/threat-dragon/assets/107138786/ae5936bb-e95d-4dfc-94f9-2974dc88f5a8)

**Expected behaviour**:
If we click on close button then new threat should not be added. New threat should only be added on clicking the [Apply] Button.

**Environment**:

- Version: (e.g. 1.3.1)
- Platform: (Web App / Desktop App)
- OS: (MacOS / Windows / Linux)
- Browser: (e.g. chrome, firefox, safari)

**To Reproduce**:

**Any additional context, screenshots, etc**:

**Comment by jgadsden** [comment] 2024-03-02 17:10
this is not a bug, in that this is the intended behavior
At  present the threat is removed by using the 'Remove' button, in a similar way to adding a new diagram, and not on closing the window
if we change this then we are breaking the consistency of the application

**Comment by itsdheerajdp** [comment] 2024-03-02 17:21
@jgadsden i thought if a user accidently clicked the New Threat Button but don't want to add the new threat so he close the window but still the new threat created which will cause a extra effort for him to remove the threat.

**Comment by jgadsden** [comment] 2024-03-04 09:30
I have created a list of actions for the threat creation and modification in #899 , so closing this issue

**Closed by jgadsden** 2024-03-04 09:30 UTC
Labels: discussion
