### ISSUE TITLE
More than one threat of same type can be added for same element of chosen threat model 

### ISSUE THREAD

**Issue by itsdheerajdp** [OWASP/threat-dragon#892] opened 2024-03-01 13:33 UTC
**Describe the bug**:
Currently we can add same type of threat infinite number of times for same element of threat model.
Ex. For STRIDE Model , We can add Spoofing type of threat 'x' Number of times which is not desirable for threat modeling.

[screen-capture.webm](https://github.com/OWASP/threat-dragon/assets/107138786/9fda712e-725d-4b55-bbeb-402206509ba9)

**Expected behaviour**:
For Same threat model , One element can have at most of one threat of one type 
ex. For a element in STRIDE model , the element can have at most of one spoofing type threat.

**Environment**:

- Version: (e.g. 1.3.1)
- Platform: (Web App / Desktop App)
- OS: (MacOS / Windows / Linux)
- Browser: (e.g. chrome, firefox, safari)

**To Reproduce**:

**Any additional context, screenshots, etc**:

**Comment by itsdheerajdp** [comment] 2024-03-01 13:40
@jgadsden If you found this as a bug then i'll work on this ...

**Comment by jgadsden** [comment] 2024-03-01 14:56
This is not a bug - it is very valid, and is often the case, that more than one threat of the same type is identified for the same component
the application is working as expected and closing this issue as "Won't Do"

**Closed by jgadsden** 2024-03-01 14:56 UTC
Labels: discussion, Won't Do
