### ISSUE TITLE
Desktop: TDD 1.3 not a trusted app for both Windows and Apple

### ISSUE THREAD

**Issue by lmcthbe** [OWASP/threat-dragon#219] opened 2020-09-14 12:05 UTC
Threat Dragon Desktop 1.3 is not recognized as a thrusted application on both Windows and Apple.

Enterprise usually does not allow non thrusted application to be installed on managed computer. TDD 1.3 can still be installed on Windows as there is still a possibility to perform the download/installation however it is completely blocked on Mac OS preventing any installation.

**Comment by lreading** [comment] 2021-08-22 20:30
@lmcthbe - [Version 1.5.3](https://github.com/OWASP/threat-dragon/releases/tag/v1.5.3) has been released which has signed/notarized MacOS installers.  Jon is working with a CA to finalize the code-signing certificate, and we expect to have signed Windows bundles in the coming weeks as well.  I'll leave this issue open and check back in when the Windows binaries are signed.

**Comment by jgadsden** [comment] 2021-09-05 10:53
Hello @lreading , I have given up on the Certum signing process for Threat Dragon - I do not _think_ it is possible to use it with electron-builder. It seems to be document signing and local executable signing only

The other certificate from Comodo needs a Windows machine + browser combination that I can not supply. If this can be overcome then it should work:
https://github.com/electron-userland/electron-builder/issues/5411

**Comment by jgadsden** [comment] 2021-09-16 14:33
Comodo looks like the best bet: 
https://comodosslstore.com/resources/comodo-code-signing-certificate-instructions/

Will make another attempt today

**Comment by jgadsden** [comment] 2021-09-27 13:39
Confirmed that Windows code signing is now in place and working. Can finally close this isse

**Closed by jgadsden** 2021-09-27 13:39 UTC
Labels: bug, documentation, version-1.5, desktop
