### ISSUE TITLE
Threat Model-Access Level Controls Defined on the model file -Github

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#10] opened 2020-06-05 06:30 UTC
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon/issues/124
and was opened by @johocurtest : 

It seems there is no ACL on the threat model file created in GitHub

Steps:

Login as User A using your GitHub account
Create a model
Share the link with User B
User B logins in to GitHub and opens model file from User A GitHub repo hyperlink
Result:
User B can change file from User A (no Read/Edit/Modify ACL)

**Comment by lreading** [comment] 2021-05-25 05:56
Since version 2 will have multiple authentication methods and back-end storage provider options, is this something that is still desired? From reading the original issue, this sounds like it's working as designed.  Could this be improved by a documentation update that warns users that anyone with read access can view the TM and anyone with read can update/delete?

**Comment by jgadsden** [comment] 2021-05-27 06:06
I agree with @lreading - from the  given scenario it seems User B has existing edit permission to the github repo, and so can not be stopped from editing User A's file. Have I got the right understanding here @johocurtest ?

We do not want to provide our own Threat Dragon access management on top of what is applied to the remote repository or filesystem etc - this will probably break at some point and be hard to debug, and may not add any  extra security for the threat model files

**Comment by lreading** [comment] 2021-06-02 19:55
Closing for now.  If you feel this was in error, please let us know. :smiley:

**Closed by lreading** 2021-06-02 19:55 UTC
Labels: enhancement
