### ISSUE TITLE
Zoom out and resizing the graph section

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/threat-dragon#191] opened 2021-06-21 07:21 UTC
Hi,

I tried to zoom out and get the full view (small map) from my threat model, but it's not possible in the UI; it would be nice to resize the graph section and zoom out or zoom in.

Bests, Ali.

**Comment by jgadsden** [comment] 2021-06-21 08:11
Hello @Ali-Razmjoo , yes indeed this would be very good to have

It has been a problem to us for a very long time - we had it in for a while but found that it could result in us losing components from the diagram. This is all to do with us using the free-to-use version of jointjs rather than the licenced version of jointjs drawing package. @lreading will be migrating threat dragon to a different drawing package for version 2.0, and this supports zoom in and zoom out directly, so we can have this feature reinstated for that version.

@lreading I have gone ahead and assigned this to you, hope that is still OK with you? This is similar to #144

**Comment by lreading** [comment] 2021-06-21 14:39
As Jon indicated, this has been re-implemented in 2.0 as we are using a new drawing package that's a bit more maintainable.  We have also implemented panning as well.  Again, 2.0 will not be released until later this year.

**Comment by lreading** [comment] 2021-06-21 14:40
I will be closing this as a duplicate of https://github.com/OWASP/threat-dragon/issues/144 (It's not immediately obvious based on the name/description).  Thanks again, Ali for the issue!

**Closed by lreading** 2021-06-21 14:40 UTC
Labels: enhancement, pending-release, version-2.0
