### ISSUE TITLE
Window size is fixed (on Mac electron)

### ISSUE THREAD

**Issue by storkinsj** [OWASP/threat-dragon#56] opened 2021-03-19 14:13 UTC
**Describe the bug**
No matter how big my screen is, my window size is fixed for threat dragon. I get a huge bottom and right side border.  It is possible to use more real estate than what is shown, but it is unnecessarily difficult, and dragging an object onto any of the edges results in a very rapid scrolling, which then has to be undone by deleting the object, then dragging the sliders back. 

**Expected behavior**
Drawable area should scale to the size of the screen. We have very large screens now some are 4k! Today we can't even make full use of a 1380X768 screen. 

**Environment**
 - Version: 1.3.1
 - Platform: Mac OS Electron Desktop App
 - OS: MacOS  Catalina
 - Browser: None

**To Reproduce**
Simply maximize the window to full size. Note: Massive borders on bottom and right side of window; drawing area remains fixed.  Most diagrams I have drawn the past 6 months have needed to be carefuly tweaked and optimized to fit inside the window.

**Any additional context, screenshots, etc**
![Screen Shot 2021-03-19 at 11 12 17 PM](https://user-images.githubusercontent.com/17778154/111793407-98216080-8908-11eb-97a1-0ffe4da12867.png)

**Comment by jgadsden** [comment] 2021-03-22 08:30
Hello @storkinsj - yes, agreed, this is not a good look for Threat Dragon. It has been a problem for a while, with @injcristianrojas raising this in issue https://github.com/OWASP/threat-dragon-desktop/issues/84 .

It is that same root cause (or so I think) in that the drawing package is a rather old version of JointJS. It should be fixed when we migrate to mxgraph in Threat Dragon version 2.0

Do you want to add your comments into the Threat Dragon Desktop repo issues ?  
https://github.com/OWASP/threat-dragon-desktop/issues

Thanks again for the suggestions, all much appreciated

**Comment by lreading** [comment] 2021-12-31 21:09
We're currently working on version 2.0 (due in 2022) which is a rewrite, and implements zoom, pan, scrolling, etc.  We changed the layout for the graph edit view so that the properties and threats are under the graph.  This gives the graph a bit more real estate, and we are working to ensure the graph size adjusts with the screen/resolution.

Here's a screenshot with the latest work in progress: https://github.com/OWASP/threat-dragon/issues/336#issuecomment-1003290329

If anyone has feedback on that or suggestions, we are all ears!!! :smile:

**Comment by jgadsden** [comment] 2023-01-17 06:31
Closing this as it has been fixed by the new drawing library for version 2.0

**Closed by jgadsden** 2023-01-17 06:31 UTC
Labels: bug, help wanted
