### ISSUE TITLE
Undo does not bring back data flows

### ISSUE THREAD

**Issue by srcnuzn** [OWASP/threat-dragon#1069] opened 2024-08-22 11:28 UTC
**Describe the bug**:

Have two processes connected by data flow. When deleting the process, the data flows are deleted, too. When undoing the action, only the process is brought back. The data flows are gone.

**Expected behaviour**:

Undo should bring back all deleted elements.

**Environment**:

- Version: 2.2
- Platform: Desktop App
- OS: Windows 11

**To Reproduce**:

1. Create two processes
2. Connect them with data flow
3. Delete one process
4. Click undo

**Any additional context, screenshots, etc**:

![2024-08-22_13h25_21](https://github.com/user-attachments/assets/4ba1b9ac-d396-45f6-9334-3425312e1f04)

**Comment by jgadsden** [comment] 2024-08-23 09:55
agreed, and this was a discussion in #640 that is now resolved in favour of the functionality in this bug report
we do not have a fix for this, it may be a feature of AntV/X6 that we can not get round, but planning this for version 2.4 in case it is possible

**Comment by srcnuzn** [comment] 2024-08-23 10:21
From all the bugs I've raised yesterday, I personally think this is the most critical one, especially because identified threats/mitigations and documentations are unintentionally, but permanently lost (with no undo possibility).

**Comment by lreading** [comment] 2024-09-13 16:10
I took a look at this and couldn't reproduce the issue... _on linux_.  I was able to reproduce this on MacOS, and @srcnuzn reported this from Windows.  I don't have a solution, but I just thought that was interesting and wanted to add here in case anyone picks this up. :smile:

**Comment by jgadsden** [comment] 2024-10-06 06:27
I can not reproduce this myself - the undo works for both electron and web versions
I suggest we get the new drawing package merged into main (sometime this month) and then retest?

**Comment by jgadsden** [comment] 2024-10-16 07:53
@srcnuzn and @lreading could you retest this when you get a chance, using the latest version
I will bump this to version 2.4 for now

**Comment by lreading** [comment] 2024-10-18 14:30
Looking good on the main branch on ubuntu 24.04 and macOS sequoia!

**Comment by lreading** [comment] 2024-12-27 17:53
This was fixed in [version 2.3.0](https://github.com/OWASP/threat-dragon/releases/tag/v2.3.0), released last month.

**Closed by lreading** 2024-12-27 17:53 UTC
Labels: bug, AntV/X6, version-2.3.1
