### ISSUE TITLE
PDF Report dialog does not show existing PDF files

### ISSUE THREAD

**Issue by srcnuzn** [OWASP/threat-dragon#1062] opened 2024-08-22 07:41 UTC
**Describe the bug**:

Existing PDF files are not shown in file save dialog (probably wrong file type filter, i.e., two dots before the PDF extension).

**Expected behaviour**:

Existing PDF files are shown in file save dialog.

**Environment**:
Version 2.2.0
Desktop App
Windows 11

**To Reproduce**:

Export PDF file into directory which contains PDF files.

**Any additional context, screenshots, etc**:

![image](https://github.com/user-attachments/assets/3cf7c72f-801f-44dd-bd06-f939ea5ca751)
![image](https://github.com/user-attachments/assets/63364e84-5ce7-4353-a0da-6203759447dc)

**Comment by jgadsden** [comment] 2024-08-23 09:33
very good to have this bug report @srcnuzn , this was a recent change because it did not work on MacOS / Linux with just `pdf` so it was changed to `.pdf` - but this now breaks it for Windows
I thik the solution is to filter for both `pdf` and `.pdf` (I had sort of hoped the dialog would have done this itself :)  )

**Comment by jgadsden** [comment] 2024-09-22 20:26
this was a fix provided by #1023 , and the fix is scheduled for version 2.3 - but is still in version 2.2 tested here
closing this as a duplicate of #1023

**Closed by jgadsden** 2024-09-22 20:26 UTC
Labels: bug, reports, version-2.3
