### ISSUE TITLE
How to set the env variables for owasp dragon in centos environment

### ISSUE THREAD

**Issue by p-pujitha** [OWASP/threat-dragon#188] opened 2021-06-07 06:46 UTC
Hi 
I have done the set up but observed some error while building the application.

**Error** :

> owasp-threat-dragon-server@1.4.0 transpile /apps/owaspInstall/threat-dragon/td.server
> babel ./src --out-dir dist

ReferenceError: Unknown plugin "@babel/plugin-transform-runtime" specified in "/apps/owaspInstall/threat-dragon/td.server/.babelrc" at 0, attempted to resolve relative to "/apps/owaspInstall/threat-dragon/td.server"
    at /apps/owaspInstall/threat-dragon/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/apps/owaspInstall/threat-dragon/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/apps/owaspInstall/threat-dragon/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/apps/owaspInstall/threat-dragon/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/apps/owaspInstall/threat-dragon/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/apps/owaspInstall/threat-dragon/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/apps/owaspInstall/threat-dragon/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/apps/owaspInstall/threat-dragon/node_modules/babel-cli/lib/babel/util.js:50:22)
    at Object.compile (/apps/owaspInstall/threat-dragon/node_modules/babel-cli/lib/babel/util.js:59:12)

To understand how to set the environment variables , observed link is not working.

**Link** : http://docs.threatdragon.org/install-webapp/setup-env.md

**Comment by jgadsden** [comment] 2021-06-07 06:55
@lreading I think you are the expert on this one, but I can have a look if you like?

**Comment by p-pujitha** [comment] 2021-06-07 06:59
Do you have idea why this error is coming ?

**Comment by jgadsden** [comment] 2021-06-08 06:13
Looking at this now. @p-pujitha could you make sure that your docs submodule is present?

It is pulled in from another repo, so if you do this command `git submodule update` in your top level threat dragon directory it will get populated.

Also could you use link http://docs.threatdragon.org/setup-env/ instead of link http://docs.threatdragon.org/install-webapp/setup-env.md and see if that works OK

This should get you started on setting up the environment variables, but I do not think this is why your `npm run start` command is failing on babel

Could you tell me some versions on `npm --version` and `node --version` ?

**Comment by lreading** [comment] 2021-06-09 20:39
Did you run npm install (including the dev dependencies) before building?  The dependency in question is in the dev dependencies in the [package.json](https://github.com/OWASP/threat-dragon/blob/main/td.server/package.json#L47), so it _should_ exist.

I'll try this out on a CentOS VM in the next day or two to see if I can reproduce.  Thanks for raising the issue!

**Comment by lreading** [comment] 2021-08-13 04:44
Because it's been quite a while, I'm going to close this issue.  If you're still having an issue, please do comment/re-open, or feel free to open a new issue! :sunglasses:

**Closed by lreading** 2021-08-13 04:44 UTC
Labels: bug
